version: "3"

services:
  app:
    container_name: "Flask_Portfolio"
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - db
    stop_signal: SIGINT

  db:
    image: mysql:8.0.32
    container_name: container-db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dba
    volumes:
      - ./db/docker-entrypoint-initdb.d
