version: "3"

services:
  app:
    container_name: "Flask_Portfolio"
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - db
      - db2
    stop_signal: SIGINT

  db:
    image: mysql:8.0.32
    container_name: container-db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

  db2:
    image: mysql:8.0.32
    container_name: admin-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PW}
    ports:
      - "32001:3306"
networks:
  talk: {}

volumes:
  db:
    driver: local